#pragma once
#include "main.h"
void runLeftWingToggle();
void runRightWingToggle();
void autoClamp();
void engageLeftWing();
void engageRightWing();
void disengageLeftWing();
void disengageRightWing();
bool isWinged();
